/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Products;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.products</code>.
     */
    public static final Products PRODUCTS = db.tables.Products.PRODUCTS;
}
